name: "CI"

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ["**[0-9]+.[0-9]+.[0-9]+*"]

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update
          sudo apt install libxcb-xfixes0-dev
      - name: Install ollama
        run: curl -fsSL https://ollama.com/install.sh | sh
      - name: Run ollama
        run: |
          ollama serve &
          ollama pull phi3:mini
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}
      - name: Unit tests
        run: cargo test --all-features
      - name: Doc tests
        run: cargo test --doc --all-features -- --show-output
      - name: Examples
        run: cargo test --examples --all-features

  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
