[package]
name = "orch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
derive_builder = "0.12.0"
dotenv = "0.15.0"
headless_chrome = { version = "1.0.5", features = ["fetch"] }
openai = "1.0.0-alpha.9"
pdf-extract = "0.6.5"
reqwest = { version = "0.11.18", features = ["blocking"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.97"
serpapi-search-rust = "0.1.1"
tokio = { version = "1.28.2", features = ["rt", "macros"] }
url = "2.4.0"
