name: Release
on:
  push:
    tags: ["[0-9]+.[0-9]+.[0-9]+"]

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Exit if not on main branch
        if: endsWith(github.event.base_ref, 'main') == false
        run: exit 1

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Publish `orch_response`
        run: cargo publish -p orch_response --token ${{ secrets.CRATES_IO_API_TOKEN }}
      
      - name: Publish `orch_response_derive`
        run: cargo publish -p orch_response_derive --token ${{ secrets.CRATES_IO_API_TOKEN }}

      - name: Publish `orch`
        run: cargo publish -p orch --token ${{ secrets.CRATES_IO_API_TOKEN }}
        
